INSERT INTO business_type_category (name)
VALUES
('Auto Accessories'),
('Auto Dealers – New'),
('Auto Dealers – Used'),
('Detail & Carwash'),
('Gas Stations'),
('Motorcycle Sales & Repair'),
('Rental & Leasing'),
('Service, Repair & Parts'),
('Towing'),
('Consultants'),
('Employment Agency'),
('Marketing & Communications'),
('Office Supplies'),
('Printing & Publishing'),
('Computer Programming & Support'),
('Consumer Electronics & Accessories'),
('Architects, Landscape Architects, Engineers & Surveyors'),
('Blasting & Demolition'),
('Building Materials & Supplies'),
('Construction Companies'),
('Electricians'),
('Engineer, Survey'),
('Environmental Assessments'),
('Inspectors'),
('Plaster & Concrete'),
('Plumbers'),
('Roofers'),
('Adult & Continuing Education'),
('Early Childhood Education'),
('Educational Resources'),
('Other Educational'),
('Artists, Writers'),
('Event Planners & Supplies'),
('Golf Courses'),
('Movies'),
('Productions'),
('Desserts, Catering & Supplies'),
('Fast Food & Carry Out'),
('Grocery, Beverage & Tobacco'),
('Restaurants'),
('Acupuncture'),
('Assisted Living & Home Health Care'),
('Audiologist'),
('Chiropractic'),
('Clinics & Medical Centers'),
('Dental'),
('Diet I& Nutrition'),
('Laboratory, Imaging & Diagnostic'),
('Massage Therapy'),
('Mental Health'),
('Nurse'),
('Optical'),
('Pharmacy, Drug & Vitamin Stores'),
('Physical Therapy'),
('Physicians & Assistants'),
('Podiatry'),
('Social Worker'),
('Animal Hospital'),
('Veterinary & Animal Surgeons'),
('Antiques & Collectibles'),
('Cleaning'),
('Crafts, Hobbies & Sports'),
('Flower Shops'),
('Home Furnishings'),
('Home Goods'),
('Home Improvements & Repairs'),
('Landscape & Lawn Service'),
('Pest Control'),
('Pool Supplies & Service'),
('Security System & Services'),
('Accountants'),
('Attorneys'),
('Financial Institutions'),
('Financial Services'),
('Insurance'),
('Other Legal'),
('Distribution, Import/Export'),
('Manufacturing'),
('Wholesale'),
('Cards & Gifts'),
('Clothing & Accessories'),
('Department Stores, Sporting Goods'),
('General'),
('Jewelry'),
('Shoes'),
('Civic Groups'),
('Funeral Service Providers & Cemetaries'),
('Miscellaneous'),
('Utility Companies'),
('Animal Care & Supplies'),
('Barber & Beauty Salons'),
('Beauty Supplies'),
('Dry Cleaners & Laundromats'),
('Exercise & Fitness'),
('Massage & Body Works'),
('Nail Salons'),
('Shoe Repairs'),
('Tailors'),
('Agencies & Brokerage'),
('Agents & Brokers'),
('Apartment & Home Rental'),
('Mortgage Broker & Lender'),
('Property Management'),
('Title Company'),
('Hotel, Motel & Extended Stay'),
('Moving & Storage'),
('Packaging & Shipping'),
('Transportation'),
('Travel & Tourism');